#!/usr/bin/env bash
#
# Writes android/keystore.properties from the credential file kept outside the
# repository, so the keystore and its password never enter git.
#
# The credential file defaults to ~/.keystores/komunikasi-release.credentials
# and is created by `npm run android:keystore`.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CRED_FILE="${KOMUNIKASI_KEYSTORE_CREDENTIALS:-$HOME/.keystores/komunikasi-release.credentials}"
PROPS="$ROOT/android/keystore.properties"

if [ ! -f "$CRED_FILE" ]; then
  echo "credential file not found: $CRED_FILE" >&2
  echo "run 'npm run android:keystore' first" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$CRED_FILE"

# The credential file uses lowercase keys; normalise to locals.
JKS="${jks:?credential file does not define jks}"
STORE_PASSWORD="${storePassword:?credential file does not define storePassword}"
KEY_ALIAS="${keyAlias:?credential file does not define keyAlias}"
KEY_PASSWORD="${keyPassword:?credential file does not define keyPassword}"

if [ ! -f "$JKS" ]; then
  echo "keystore not found: $JKS" >&2
  exit 1
fi

# storeFile is resolved by Gradle relative to android/, so keep it repo-relative.
REL_JKS="${JKS#"$ROOT"/}"

umask 077
cat > "$PROPS" <<EOF
# Generated by scripts/setup-signing.sh — do not commit (already gitignored).
storeFile=$REL_JKS
storePassword=$STORE_PASSWORD
keyAlias=$KEY_ALIAS
keyPassword=$KEY_PASSWORD
EOF

echo "wrote $PROPS"
echo "  keystore : $REL_JKS"
echo "  alias    : $KEY_ALIAS"
